export type Artist = {
  id: string,
  avatar: string,
  name: string,
  born: string,
  educations?: string[],
  description?: string,
  email: string,
  password: string,
  phone: string,
  facebookUrl?: string,
  IGUrl?: string,
  createdAt?: string,
  updatedAt?: string,
}
